### ISSUE TITLE
filtered_feature_bc_matrix.h5

### ISSUE THREAD

**Issue by saramoein372** [zktuong/dandelion#100]
Hi Kelvin,

After saying thanks, I have a question: where "filtered_feature_bc_matrix.h5" file is generated? Is it from cell ranger? What is the format of this file? What are rows and what are columns?

Thanks,
Sara

**Comment by zktuong** [comment]
Yes it’s a cellranger output file. You will have to figure out the file format yourself as it’s not a dandelion specific problem.
