### ISSUE TITLE
Problems with manual preprocessing

### ISSUE THREAD

**Issue by christie-ga** [zktuong/dandelion#126]
Hi Kelvin, 

I am trying to run the manual preprocessing with the example data, but I keep getting a few errors: 

1. When doing: 
ddl.pp.reassign_alleles(samples[:2], combined_folder = 'tutorial_scgp1', germline = wd+"database/germlines/imgt/human/vdj")

I get the following output and no plots:
...
Concatenating objects
      Running tigger-genotype with novel allele discovery.
      Novel allele discovery execution halted.
      Attempting to run tigger-genotype without novel allele discovery.
     Insufficient contigs for running tigger-genotype. Defaulting to original heavy chain v_calls.
            Reconstructing heavy chain dmask germline sequences with v_call.
...
and at the end:
... Although tigger-genotype was not run successfully, file will still be saved with `_genotyped.tsv`extension for convenience.

2. When running: 
ddl.pp.assign_isotypes(samples, blastdb=wd+"database/blast/human/human_BCR_C.fasta")

I get: 
BLAST Database error: Error: Not a valid version 4 database.

I am using the databases from your github (/container/database) which I downloaded. 

It would be great if you could tell me what I am doing wrong. 

Best, 
Christiane

**Comment by zktuong** [comment]
Hi Christiane, 

thanks for your interest in using this package.

For #1, it's just a warning message that you can ignore in most cases. I'm not sure exactly why there isn't a plot. If you just do a simple plot with `seaborn`, do you see anything?

For #2, 
Can you run the following:
```python
ddl.utl.makeblastdb(ref = "container/database/blast/human/human_BCR_C.fasta")
```

just swap out `container/database` to actual path.

After you run this, the rest should hopefully work.

**Comment by christie-ga** [comment]
Hi Kelvin, 

thank you for getting back to me so quickly!

For 1)
- I am still not sure that it is running correctly. I am running it with the same data as you do in your tutorial, but you get the following output which I do not get: 
Concatenating objects
      Running tigger-genotype with novel allele discovery.
      Reassigning alleles
            Reconstructing heavy chain dmask germline sequences with v_call_genotyped.
            Reconstructing light chain dmask germline sequences with v_call.
      For convenience, entries for light chain `v_call` are copied to `v_call_genotyped`.
Returning summary plot

- If I do a simple plot with seaborn it works fine...

For 2), 
thanks!! That fixed the problem

Best, 
Christiane

**Comment by zktuong** [comment]
hmm, what if you add `save_plot=True` into the call. do you see a pdf output?

**Comment by christie-ga** [comment]
I figured out that it works when I export the paths to the databases to .bash_profile instead of specifying them in the call. When doing that it seems to run well for the second set of samples (samples[2:], combined_folder = 'tutorial_scgp2') and I get the same plot as shown in your tutorial. 

However, for the first set of samples (samples[:2], combined_folder="tutorial_scgp1") I get the following error message and not all the files are created:

Error in findNovelAlleles(db, germline_db = igv, v_call = v_call, j_call = j_call,  : 
  Not enough sample sequences were assigned to any germline:
  (1) germline_min is too large or
  (2) sequences names don't match germlines.
Execution halted

I get a plot now, but it looks differently than the one from your tutorial...

**Comment by zktuong** [comment]
ok great!

The error message you are seeing is just part of the output from tigger when it cannot work due to insufficient contigs to run the pipeline. I've coded in a bit to catch the failures and go a separate path so it doesn't cause the entire function to fail. 

Perhaps i should add a way to hide these messages to prevent confusion.

I've recently recompiled the notebook in the devel branch. Are your plots still different from those?

**Comment by christie-ga** [comment]
I am not so much confused by the error message itself but by the fact that you don't seem to get this error message in the tutorial and that I get different results (they are also different from the plot in the devel branch) even though I think I use the same data (and database)? Maybe it is not important though... I would just like to understand it. Could it be due to differing tigger versions?

**Comment by zktuong** [comment]
hmm I'm not sure. It could be that, or the starting datasets changed somehow, or were corrupted somehow.

Anyway, it's not a big issue imo. You can ignore the `v_call_genotyped` column for the rest of the pipeline and just use `v_call` going forward.

**Comment by christie-ga** [comment]
Ok - thank you!
