### ISSUE TITLE
dandelion on bulk data

### ISSUE THREAD

**Issue by saramoein372** [zktuong/dandelion#160]
### Description of the question

Hi Kelvin,

I have a question about how to run the dandelion on bulk data? Cell  ranger output are only generated on single cell.
But dandelion needs filtered_contig_annotation.csv and filtered_contig.fasta.

Would you please help me to solve this issue, when I can not run cell ranger on my data?

Thanks,
Sara

### Any error message produced by the code above

```pytb
NA
```

### OS information

NA

### Version information

NA

### Additional context

NA

**Comment by saramoein372** [comment]
Thanks Kelvin.
Then what input data I should use to generate the filtered_contig_dandelion.tsv file? 
Can you provide more details about the steps? Sorry, I am not so clear about what steps I need to do.

Thanks,
Sara

**Comment by zktuong** [comment]
It depends on what the manufacturer of your BCR-seq library kit reccomends. Off the top of my head, you would have to either use [presto](https://presto.readthedocs.io/en/stable/) or [MiXCR](https://mixcr.readthedocs.io/en/master/license.html) and then [export as AIRR format](https://github.com/milaboratory/mixcr/wiki/Export-of-AIRR-formatted-tsv) if your data is in fastq format. Usually your library kit provider will tell you directly what you should use, as they come with custom primers information which you will need to provide into those softwares anyway.

If your data is already in fasta format, you can i) run MiXCR in shotgun mode, ii) use [igblastn](https://ncbi.github.io/igblast/cook/examples.html), iii) use IMGT/High V-QUEST(https://www.imgt.org/IMGTindex/IMGTHighV-QUEST.php) and obtain the AIRR files.

As this sounds like it is outside the immediate scope of dandelion as it doesn't handle those bits above, your questions would probably be better placed directed at the developer of those other softwares.

Any more help/information about this would require substantially more involvement from me, and would require a formal e-mail to my supervisor (Professor Menna Clatworthy <mrc38@medschl.cam.ac.uk>] to request a collaboration.
