### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by saramoein372** [zktuong/dandelion#174]
### Description of the question

Hi Kelvin,

I have a question when generating the networks: 
what is the meaning of no-contig in the plot of vdj_istype? How we interpret that?

Thanks,
Sara

**Comment by zktuong** [comment]
it means there's no BCR/TCR associated with the cell barcode (e.g. non-T/B cells). you can just ignore these ones

**Comment by saramoein372** [comment]
Thanks Kelvin.
I have two more questions:
The network in the dandelion clusters are generated using minimum spanning tree. Right?
what is the threshold of similarity used for the mst in dandelion?

Thnaks.

**Comment by zktuong** [comment]
> The network in the dandelion clusters are generated using minimum spanning tree. Right?

Yes.

> what is the threshold of similarity used for the mst in dandelion?

There is no threshold.
