### ISSUE TITLE
local variable 'h_ccall_p_igm_count' referenced before assignment

### ISSUE THREAD

**Issue by YuxuanZheng94** [zktuong/dandelion#182]
Dear developers,
When I used the function `filter_contigs` under `sc-dandelion` (version: 0.2.5 development) as`vdj = ddl.pp.filter_contigs(bcr)`, the error raised `UnboundLocalError: local variable 'h_ccall_p_igm_count' referenced before assignment`. And then I changed the version of `sc-dandelion` to 0.2.4, this error still existed. However, when I changed the version into 0.2.1, this problem was resolved. Would you tell me what happened here?

**Comment by zktuong** [comment]
hi @YuxuanZheng94, thanks for reporting this bug!

I'm currently travelling so will be a bit slow in fixing this but i'm looking into perhaps by the end of the week. In the mean time, can you paste for me the full error trace? just want to confirm which line number in the code is this tripping at.

**Comment by zktuong** [comment]
hi @YuxuanZheng94, can you try and install with `pip install git+https://github.com/zktuong/dandelion.git@fix_unreference_variable-182` and see if the error appears?

**Comment by YuxuanZheng94** [comment]
> hi @YuxuanZheng94, can you try and install with
> 
> ```shell
> pip install git+https://github.com/zktuong/dandelion.git@fix_unreference_variable-182
> ```
> 
> and see if the error appears?

This update works! There is no error reported! Thank you very much!
