### ISSUE TITLE
fastq 

### ISSUE THREAD

**Issue by saramoein372** [zktuong/dandelion#213]
### Description of the issue

Hi Kelvin,

I was wondering if you can share your BCR fastq file for one of the healthy control samples in your covid paper?

Thank you,
Sara

**Comment by zktuong** [comment]
Hi Sara,

unfortunately i would not be able to simply provide the fastqs of the samples as they require data access control agreements between your institution and Cambridge NIHR Bioresource and University of Newcastle. The page which has this info is here: https://ega-archive.org/studies/EGAS00001005465. I believe the Sanger data doesn't have healthy samples so you wouldn't need that.

Please consult your group leader and also your research contracts office about the procedures you would need to adhere to as it will involve the legal teams on both sides (your side and Cambridge/Newcastle side) to have an agreement before any data sharing can be enabled from the European Genome-Phenome Archive.
