### ISSUE TITLE
Running the google colab version, I am getting a type error at step 3 when importing dandelion as ddl

### ISSUE THREAD

**Issue by savitaj** [zktuong/dandelion#270]
Hi Dr. Tuong, 

Thanks for the tool. I am getting error while using google colab at step 3 

# import and show versions
import dandelion as ddl
ddl.logging.print_header()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-11-515e438d9f17>](https://localhost:8080/#) in <cell line: 2>()
      1 # import and show versions
----> 2 import dandelion as ddl
      3 ddl.logging.print_header()

7 frames
[/usr/local/lib/python3.10/site-packages/scanpy/plotting/_utils.py](https://localhost:8080/#) in <module>
     33 
     34 
---> 35 class _AxesSubplot(Axes, axes.SubplotBase, ABC):
     36     """Intersection between Axes and SubplotBase: Has methods of both"""
     37 

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
 

Could you please advise. Thanks in advance.

**Comment by zktuong** [comment]
forgot about the networkx patch #258 

so until i update the pypi version, the full installation line should be `!pip install -q sc-dandelion scanpy[leiden] networkx==2.7`

**Comment by zktuong** [comment]
hi @savitaj, i'm closing this issue as the new notebook link has incorporated the changes to make it work again. thanks again for letting me know.

**Comment by savitaj** [comment]
Thanks a lot Dr. Tuong. It is working now. Really appreciate it. 

I am also trying to run Dandelion separately on Jupyter notebook after installing all the required packages listed . Facing some version conflict issues with python packages there as well. I will raise a different ticket for that. Thanks again. 

Best regards, 
Savita
