### ISSUE TITLE
Singularity not finding meta file

### ISSUE THREAD

**Issue by obrien-james** [zktuong/dandelion#274]
### Description of the bug

Hi, 

Im having trouble getting the Dandelion pre-processing working using the singularity container. 

I have installed singularity into a conda environment (I don't have root access on a shared HPC cluster). 

I have pulled the latest dandelion container, changed to the directory that holds individual samples in separate sub folders and ran:

`singularity run -B $PWD /home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/sc-dandelion_latest.sif dandelion-preprocess --filter_to_high_confidence `

This results in the following error:

"FileNotFoundError: Path to fasta file is unknown. Please specify path to fasta file or folder containing fasta file. Starting folder should only contain 1 fasta file."

Each sample folder had both all_ and filtered_contig files. 

I then tried to run 

`singularity run -B $PWD /home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/sc-dandelion_latest.sif dandelion-preprocess --filter_to_high_confidence  --file_prefix filtered`

Same error.

I have tried running both commands with only each sample folder containing the filtered_contig files and both commands result in the same error. 

I then tried to use a meta file (as a previous issue suggested was a solution)

`singularity run -B $PWD /home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/sc-dandelion_latest.sif dandelion-preprocess --filter_to_high_confidence --meta /home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/raw/meta.csv`

This resulted in the following error

FileNotFoundError: [Errno 2] No such file or directory: '/home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/raw/meta.csv'

The initial output shows:

```
Beginning preprocessing

command line parameters:
: 
--------------------------------------------------------------
    --meta = /home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/raw/meta.csv
    --chain = ig
    --org = human
    --file_prefix = filtered
    --sep = _
    --flavour = strict
    --skip_format_header = False
    --filter_to_high_confidence = True
    --keep_trailing_hyphen_number = False
    --skip_reassign_dj = False
    --clean_output = False
--------------------------------------------------------------
```

I can open the meta.csv file with `nano /home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data/raw/meta.csv` without issue. 

Any suggestions as to what to try next

**Comment by zktuong** [comment]
hi @obrien-james, i'm wondering if your `$PWD` is not `/home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data` so it can't actually access your `meta.csv` file? would it help if you also bind `/home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data`

like:
```bash
export SOMEPATH=/home/jo388/rds/rds-cad_bfx_projects-OsGdhNr6c2U/jo388/BCR/data

singularity run -B $PWD,$SOMEPATH $SOMEPATH/sc-dandelion_latest.sif dandelion-preprocess --filter_to_high_confidence --meta $SOMEPATH/raw/meta.csv

```

**Comment by obrien-james** [comment]
Thanks for the reply. 

Your suggestion worked. 

However this morning I attempted again, but ran the code from my base conda environment, which essentially only has python and it without the extra bind variables seemed to work too.

**Comment by zktuong** [comment]
ok closing this issue now.
