### ISSUE TITLE
Installation error using Singularity: FATAL: While getting image info: error decoding image: invalid ObjectId in JSON

### ISSUE THREAD

**Issue by hoonghim** [zktuong/dandelion#275]
### Description of the question

Dear Dr. Tuong,

Hello, thank you for pvoviding your wonderful scVDJ-seq analysis tool, Dandelion.

I have trouble installing Dandelion using Singularity.

I am working on the server in mylab and here is the information of the server and Singularity.

`$ singularity --version`
`singularity version 3.2.0-1`

`$ cat /etc/os-release`
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"`
NAME="Ubuntu"`
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```

I had no problems installing scanpy, graph-tool and sc-dandelion using conda and pip.

I was unable to update Singularity because this was installed in our server and used by other lab members.

### Minimal example

```python
singularity pull library://kt16/default/sc-dandelion:latest
```

### Any error message produced by the code above

```pytb
FATAL:   While getting image info: error decoding image: invalid ObjectId in JSON: "kt16/default/sc-dandelion:sha256.afdaf7ca5a9183a771ae3030542b6d57b846d5db8087c158e03ef0e2eb133c81"
```

### OS information

Ubuntu 22.04.1 LTS

### Version information

ddl.logging.print_versions()
dandelion==0.3.2 pandas==2.0.2 numpy==1.24.3 matplotlib==3.7.1 networkx==3.1 scipy==1.5.3

### Additional context

If there is a guideline to follow the tutorial without Singularity, or solution to solve the above issue, it would be very helpful to my research.

Sincerely,

Seunghoon

**Comment by zktuong** [comment]
hi @hoonghim, thank you for the interest in dandelion.

I think your singularity version is too old. the image was build using v3.6.1 and i suspect between v3.2.0-1 to v.3.6.1, there could be some differences in how singularity may be trying to download the image.

Simply providing you the current image as a stand alone file won't likely work as i recall trying it with someone else. Seems like an an older singularity can't handle a new image but i'm happy to give it a try. send me an email at z.tuong@uq.edu.au and i'll send you a link to download the image manually.

**Comment by Eagle-Swift** [comment]
Hi, sorry for interrupt. I have exactly the same problem. Can you  give me a link or, if it is possible, can you give a link that I can use wget to download  the sif ?
Thank you for help.

**Comment by zktuong** [comment]
Hi @Eagle-Swift. sure thing. I'll post the link here by tomorrow as my internet is patchy at the moment

**Comment by zktuong** [comment]
@Eagle-Swift here you go:
https://filesender.aarnet.edu.au/?s=download&token=4ff13e54-3fae-4648-961d-ddd02baad4f0
