### ISSUE TITLE
Define clones within each group

### ISSUE THREAD

**Issue by Ngort** [zktuong/dandelion#279]
### Is your feature request related to a problem?

I have data from multiple replicates pooled together, each with an identity assigned by a metadata column. I want the defined clones to be within each group, and the edges across groups to be of zero weight.

Right now the DefineClones.py code run is defined as:
```
    cmd = [
        "DefineClones.py",
        "-d",
        h_file1,
        "-o",
        h_file2,
        "--act",
        action,
        "--model",
        model,
        "--norm",
        norm,
        "--dist",
        str(dist_),
        "--nproc",
        str(nproc),
        "--vf",
        v_field,
    ]

```
Could we add something that serves as argument for `--gf` aka `--group_fields`?

### Describe the solution you'd like

 I want the defined clones to be within each group, and the edges across groups to be of zero weight.

### Describe alternatives you've considered

Slicing the data and running the algorithm.

**Comment by zktuong** [comment]
Hi @Ngort, thanks - yes i can certainly add this.

I'm currently thinking if i add a free form list `[]` that you can specify that option, and any other options so it would be like:
```
cmd_final = cmd + user_additional_cmd
```

**Comment by Ngort** [comment]
This is perfect! It works like a charm.
