### ISSUE TITLE
Add outfile_dir to define_clones

### ISSUE THREAD

**Issue by Ngort** [zktuong/dandelion#282]
### Is your feature request related to a problem?

Right now, if one runs define_clones on a Dandelion object, the wrapper does the following:

```
    if os.path.isfile(str(vdj_data)):
        tmpFolder = "{}/tmp".format(os.path.dirname(vdj_data))
        outFolder = "{}".format(os.path.dirname(vdj_data))
    else:
        import tempfile

        tmpFolder = "{}/tmp".format(tempfile.TemporaryDirectory().name)
        outFolder = "{}".format(tempfile.TemporaryDirectory().name)

```
It should allow for saving the output as a file even if the input wasn't one.

### Describe the solution you'd like

Add an argument `outfile_dir` that fits into that if-statement.

**Comment by zktuong** [comment]
hi @Ngort, as this function returns a `Dandelion` object, you could also just do:

```python
ddl.tl.define_clones(vdj, ...)
vdj.write_airr("after_define_clones.tsv")
```

this would probably be simpler than trying to rejig the code inside

**Comment by zktuong** [comment]
i'm added in #288 the option `out_dir` to `ddl.tl.define_clones`

**Comment by Ngort** [comment]
Thank you!
