### ISSUE TITLE
Igblastn error for Human and not Mouse

### ISSUE THREAD

**Issue by Kfirinb** [zktuong/dandelion#390]
### Description of the bug

Hello,
I have ran the following command on my data:

**tracer assemble -s Hsap -c /home/kfir/tracer/tracer.conf -p 2 /home/kfir/Pemphigus_TCR_Analysis/TAU260324/1/C2_exp78_S1_L001_R1_001.fastq.gz /home/kfir/Pemphigus_TCR_Analysis/TAU260324/1/C2_exp78_S1_L001_R2_001.fastq.gz cell /home/kfir/Pemphigus_TCR_Analysis/TAU260324/1/tracer_C2_exp78_S1_L001**

And in the Igblastn step it returns the following error:

**##Running IgBLAST##
CMD failed:
/home/kfir/ncbi-igblast-1.22.0/bin/igblastn -germline_db_V /home/kfir/tracer/resources/Hsap/igblast_dbs/TCR_V.fa -germline_db_D /home/kfir/tracer/resources/Hsap/igblast_dbs/TCR_D.fa -germline_db_J /home/kfir/tracer/resources/Hsap/igblast_dbs/TCR_J.fa -domain_system imgt -organism human -ig_seqtype TCR -show_translation -num_alignments_V 5 -num_alignments_D 5 -num_alignments_J 5 -outfmt 3 -auxiliary_data optional_file/human_gl.aux -query /home/kfir/Pemphigus_TCR_Analysis/TAU260324/1/tracer_C2_exp78_S1_L001/cell/Trinity_output/cell_TCR_A.Trinity.fasta

BLAST query/options error: Germline annotation database human/human_TR_V could not be found in [internal_data] directory
Please refer to the BLAST+ user manual.**

My IGDATA variable is set as **/home/kfir/ncbi-igblast-1.22.0/bin**.

And oddly enough this command runs with no errors when I set '-s Mmus'. But obviously, the results are of no use because my data is human.

What can be done to fix this? Am I the first one to encounter this behavior?

**Comment by zktuong** [comment]
Hi, this isn't a `dandelion` error - you should direct this to [`tracer`](https://github.com/Teichlab/tracer)
