### ISSUE TITLE
error dandelion/utilities/_core.py KeyError: 'trbc*'.

### ISSUE THREAD

**Issue by lishuangshuang0616** [zktuong/dandelion#396]
### Description of the question

Hi @zktuong，

When I using ddl.read_10x_airr or ddl.read_10x_vdj to read non-10x data, I encounter the error dandelion/utilities/_core.py KeyError: 'trbc*'. It seems that the annotation results do not match Dandelion. Is there a good way to resolve this?
![image](https://github.com/zktuong/dandelion/assets/49019821/c1b430f7-fd19-4f0d-9e8e-a8cd9f50545e)

### Any error message produced by the code above

```pytb
2078 if isinstance(k, str):
   2079     if report_productive_only:
   2080         isotype.append(
   2081             "|".join(
   2082                 [
   2083                     str(z)
   2084                     for z, pp in zip(
   2085                         [
-> 2086                             conversion_dict[y.split(",")[0].lower()]
   2087                             for y in [
   2088                                 re.sub("[0-9]", "", x)
   2089                                 for x in k.split("|")
   2090                             ]
   2091                         ],
   2092                         p.split("|"),
   2093                     )
   2094                     if pp in TRUES
   2095                 ]
   2096             )
   2097         )
   2098     else:
   2099         isotype.append(
   2100             "|".join(
   2101                 [
   (...)
   2111             )
   2112         )

KeyError: 'trbc*'
```

### Version information

dandelion==0.3.7 pandas==2.2.2 numpy==1.26.4 matplotlib==3.9.0 networkx==3.3 scipy==1.14.0

**Comment by zktuong** [comment]
thanks. @lishuangshuang0616 for alerting me to this. 

I can fix this up in a future PR but for now, i would reccomend for you to add `return_dandelion=False` as a start. This will give you the AIRR formatted data frame:

```python
df = ddl.read_10x_vdj(..., return_dandelion = False)
```

Then, you can stash the current `c_call` column as a separate column e.g. `original_c_call`, get rid of the allelic calls in the `c_call` and then reload dandelion and see if it loads up properly:

```python
import re
df["original_c_call"] = df["c_call"]
df["c_call"] = [re.sub("[*][0-9][0-9]", "", str(c)) for c in df["c_call"]]
vdj = ddl.Dandelion(df)
```

hope that helps!

**Comment by zktuong** [comment]
or try installing #397 and see if it helps?

```bash
pip install git+https://www.github.com/zktuong/dandelion@fix-isotype-parsing
```

**Comment by lishuangshuang0616** [comment]
Thank you very much for your help.
