### ISSUE TITLE
Error when running ddl.pp.quantify_mutations()

### ISSUE THREAD

**Issue by palak-genge** [zktuong/dandelion#400]
### Description of the question

I'm running this line of code:

``` ddl.pp.quantify_mutations(vdj) ```

and keep running into errors indicating that my object does not have certain columns.
ie.
```
RRuntimeError: Error in (function (db, sequenceColumn = "sequence_alignment", germlineColumn = "germline_alignment_d_mask",  : 
  The column germline_alignment_d_mask was not found
```
But I have read in the 10x airr rearrangement file as I believe I was meant to but am now wondering if I'm missing something. Is there a different file I should be reading in to make my vdj object? The documentation is unclear to me, I'd really appreciate if you can point me in the right direction! Thanks for your help!

Code I ran to make vdj object:
``` vdj = ddl.read_10x_airr('EXP-00723-P1_PB02183-172_airr_rearrangement_scBCR.tsv') ```

vdj object info:
``` 
Dandelion class object with n_obs = 8486 and n_contigs = 18917
    data: 'cell_id', 'clone_id', 'sequence_id', 'sequence', 'sequence_aa', 'productive', 'rev_comp', 'v_call', 'v_cigar', 'd_call', 'd_cigar', 'j_call', 'j_cigar', 'c_call', 'c_cigar', 'sequence_alignment', 'germline_alignment', 'junction', 'junction_aa', 'junction_length', 'junction_aa_length', 'v_sequence_start', 'v_sequence_end', 'd_sequence_start', 'd_sequence_end', 'j_sequence_start', 'j_sequence_end', 'c_sequence_start', 'c_sequence_end', 'consensus_count', 'umi_count', 'is_cell', 'Well_ID', 'original_barcodes', 'locus', 'rearrangement_status'
    metadata: 'clone_id', 'clone_id_by_size', 'locus_VDJ', 'locus_VJ', 'productive_VDJ', 'productive_VJ', 'v_call_VDJ', 'd_call_VDJ', 'j_call_VDJ', 'v_call_VJ', 'j_call_VJ', 'c_call_VDJ', 'c_call_VJ', 'junction_VDJ', 'junction_VJ', 'junction_aa_VDJ', 'junction_aa_VJ', 'v_call_B_VDJ', 'd_call_B_VDJ', 'j_call_B_VDJ', 'v_call_B_VJ', 'j_call_B_VJ', 'c_call_B_VDJ', 'c_call_B_VJ', 'productive_B_VDJ', 'productive_B_VJ', 'umi_count_B_VDJ', 'umi_count_B_VJ', 'v_call_VDJ_main', 'v_call_VJ_main', 'd_call_VDJ_main', 'j_call_VDJ_main', 'j_call_VJ_main', 'c_call_VDJ_main', 'c_call_VJ_main', 'v_call_B_VDJ_main', 'd_call_B_VDJ_main', 'j_call_B_VDJ_main', 'v_call_B_VJ_main', 'j_call_B_VJ_main', 'isotype', 'isotype_status', 'locus_status', 'chain_status', 'rearrangement_status_VDJ', 'rearrangement_status_VJ' 
```

### Any error message produced by the code above

--------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
Cell In[53], line 1
----> 1 ddl.pp.quantify_mutations(vdj)

File /home/jupyter/bcr/dandelion/preprocessing/_preprocessing.py:2396, in quantify_mutations(data, split_locus, sequence_column, germline_column, region_definition, mutation_definition, frequency, combine, **kwargs)

File /home/jupyter/envs/dandelion_bcr_tcr/lib/python3.9/site-packages/rpy2/robjects/functions.py:208, in SignatureTranslatedFunction.__call__(self, *args, **kwargs)
    206         v = kwargs.pop(k)
    207         kwargs[r_k] = v
--> 208 return (super(SignatureTranslatedFunction, self)
    209         .__call__(*args, **kwargs))

File /home/jupyter/envs/dandelion_bcr_tcr/lib/python3.9/site-packages/rpy2/robjects/functions.py:131, in Function.__call__(self, *args, **kwargs)
    129     else:
    130         new_kwargs[k] = cv.py2rpy(v)
--> 131 res = super(Function, self).__call__(*new_args, **new_kwargs)
    132 res = cv.rpy2py(res)
    133 return res

File /home/jupyter/envs/dandelion_bcr_tcr/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py:45, in _cdata_res_to_rinterface.<locals>._(*args, **kwargs)
     44 def _(*args, **kwargs):
---> 45     cdata = function(*args, **kwargs)
     46     # TODO: test cdata is of the expected CType
     47     return _cdata_to_rinterface(cdata)

File /home/jupyter/envs/dandelion_bcr_tcr/lib/python3.9/site-packages/rpy2/rinterface.py:869, in SexpClosure.__call__(self, *args, **kwargs)
    862     res = rmemory.protect(
    863         openrlib.rlib.R_tryEval(
    864             call_r,
    865             call_context.__sexp__._cdata,
    866             error_occured)
    867     )
    868     if error_occured[0]:
--> 869         raise embedded.RRuntimeError(_rinterface._geterrmessage())
    870 return res

RRuntimeError: Error in (function (db, sequenceColumn = "sequence_alignment", germlineColumn = "germline_alignment_d_mask",  : 
  The column germline_alignment_d_mask was not found

**Comment by zktuong** [comment]
hi @palak-genge,

Yes unfortunately, you have to run the full pipeline as that's only when those columns will be available.

this is the manual way:
https://sc-dandelion.readthedocs.io/en/latest/notebooks/1_dandelion_preprocessing-10x_data.html

and this is through singularity if you have access to it (Reccommended):
https://sc-dandelion.readthedocs.io/en/latest/notebooks/Q1-singularity-preprocessing.html

You will see in those two pages what files you will need.

**Comment by palak-genge** [comment]
> hi @palak-genge,
> 
> Yes unfortunately, you have to run the full pipeline as that's only when those columns will be available.
> 
> this is the manual way: https://sc-dandelion.readthedocs.io/en/latest/notebooks/1_dandelion_preprocessing-10x_data.html
> 
> and this is through singularity if you have access to it (Reccommended): https://sc-dandelion.readthedocs.io/en/latest/notebooks/Q1-singularity-preprocessing.html
> 
> You will see in those two pages what files you will need.

Hello! Thanks for getting back to me! I have run the preprocessing, which file from the output of the preprocessing would the correct information? I tried reading in this file: 
exp##_filtered_contig_igblast.tsv
but I got an error that said the column for umi_count was missing.

**Comment by palak-genge** [comment]
Got it to run! Thanks for the help! 
Just to mention this, I think the file that I ended up using to run this function was not out put in the correct place when running the pipeline. I'm not sure why but it ended up in the tmp folder and didn't end up getting moved into the dandelion directory where it shows it should be in the directory tree on the manual preprocessing page. It seemed like all the steps ran without issue so I wasn't sure if there was something I was missing under the hood that would have prevented it from being moved up into that folder with the correct naming convention.
