### ISSUE TITLE
Gene expression scRNA-seq

### ISSUE THREAD

**Issue by Jiawei-Xing** [zktuong/dandelion#423]
### Description of the question

Hello, I don't have 10x VDJ libraries for my cells, is it possible to use gene expression scRNA-seq as the input? Thanks!

**Comment by zktuong** [comment]
Hi @Jiawei-Xing, unfortunately no as dandelion is meant for TCR/BCR data. If you have 5' gene expression data, you can consider using TRUST4 to reconstruct the TCR/BCR data and then come back to dandelion?
