### ISSUE TITLE
Remove skbio dependency / clean up dependencies

### ISSUE THREAD

**Issue by grst** [zktuong/dandelion#58]
Hi @zktuong, 

I am having issues testing the `to_dandelion` on the CI, because installation of `scikit-bio` fails. This is a known problem and will be fixed in the next skbio release, but as I didn't find any usage of this package in dandelion, it might be easiest to just remove it. 

In general, it would be great if you could clean up the `requirements.txt` to include only packages you really need. The fewer packages, the more likely dandelion is to install without issues. 

Cheers, 
Gregor

**Comment by zktuong** [comment]
Hi @grst, it's actually required for the diversity functions https://github.com/zktuong/dandelion/blob/master/dandelion/tools/_diversity.py

I can switch that to only import when the actual function is called instead of when the module is loaded. 
That might solve the issue.

**Comment by grst** [comment]
I see! 

Weird that I didn't find it... seems the github search isn't the best :shrug: 
I guess it makes sense to keep it then. I can use a workaround until skbio finally releases the next version.
